### TensorFlow Basic Notes


In [162]:
import tensorflow as tf
import numpy as np

def print_msg( str1, str2 ):
    "This prints a msg.."
    print str1
    print str2 + "\n"
    return

# Open a session
with tf.Session() as sess:
    # create a constant
    cons_1 = tf.constant(1.0, np.float32,[3,8])
    # eval() is the trigger to get the result, where is also the graph computes.
    print_msg("cons_1", str(cons_1.eval()))
    
    cons_2 = tf.constant(2.0, shape=[4]) # shape=[4] means the 1-d array with columns 4.
    print_msg("cons_2", str(cons_2.eval()))

    # simple calc
    cons_3 = tf.constant([4.0, 5.0, 6.0, 7.0])
    output = tf.add(cons_2, cons_3)
    print_msg("Cons2 + Cons3:", str(output.eval()))
    
    # reshape
    cons_1r = tf.reshape(cons_1, shape=[4,6])
    print_msg("Reshape Cons1:", str(cons_1r.eval()))
    
    # range
    cons_3 = tf.range(1, 19)
    print_msg("cons_3", str(cons_3.eval()))
    cons_3r = tf.reshape(cons_3, shape=[3, 6])
    print_msg("Reshape cons_3:", str(cons_3r.eval()))
    

cons_1
[[ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]]

cons_2
[ 2.  2.  2.  2.]

Cons2 + Cons3:
[ 6.  7.  8.  9.]

Reshape Cons1:
[[ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]]

cons_3
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]

Reshape cons_3:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]



### Tensors
    
>"*A vector is a 1-d array and is known as a 1st-order tensor. 
  A matrix is a 2-d array and a 2nd-order tensor. 
  The "flow" part of the name refers to computation flowing through a graph.*" -- T.F.
    
a vector is a single dimensional array. v(1i) means the array [1].
a plane vector is a 1 dimensional array. v(3i, 2j) => [3, 2]
a space vector is a 1 dimensional array. v(3i, 2j, 4z) => [3, 2, 4]
a vector of dimension n could be representing by an array of n elements.
    
#### a matrix is a 2-dimensional array. 
$\begin{bmatrix}
        1. \\
        2. \\
        3. \\
\end{bmatrix}$ => 
[ [1], [2], [3] ]
    
a normal matrix is like:
$\begin{bmatrix}
        2. & 4. & 5. \\
        3. & 10. & 6. \\
        11. & 9. & 3. \\
\end{bmatrix}$  => 
[ [ 2, 4, 5],
  [3, 10, 6],
  [11, 9, 3] ]
    
#### Temp-conclusion
Tensor is something multi-dimensional, especially useful in a large dimensional situation, and it has some same properties as vectors & matrices. e.g. calculations ..

#### tensor.eval()
After a graph has been launched in a session, the value of a Tensor can be computed by Session.run(). **Note** that tensor.eval() is a shortcut for tf.get_default_session().run(t).

### Variables
"*Variable is used to hold and update parameters. They are in-memory buffers containing tensors. They must be explicitly initialized. e.g. tf.Variable(tf.zeros([1,2])) They can be saved during and after training to disk and can be restored to exervise or analyze the model later.*" --TF.Doc

#### Initialization
Two ways to initialize variables.
- tf.initialize_variables(var_list, name=optional)
- tf.initialize_all_variables()

#### Assignment
tf.assign(ref, value, ..)
What 'tf.assign()' does is actually reset a **ref** with a new **value**.


### Operation
>"*Represents a graph node that performs computations on tensors.*" --TF.Doc

In tensorflow process, the Operation takes zero or more Tensor objects as input, and produces zero or more Tensors as output. e.g. tf.matmul().

Operation can be executed with Session.run(op). **Note** that Op.run() is a shortcut for tf.get_defualt_session().run(op).

In [179]:
# Example for variables
with tf.Session() as sess:
    
    a = tf.Variable(tf.zeros([1,2]))
    b = tf.Variable(tf.random_uniform([1,2]))  
    
    # execute operation.
    tf.initialize_all_variables().run()
    
    # compute and print value of Tensors.
    print_msg("Var A:", str(a.eval()))
    print_msg("Var B:", str(b.eval()))
    

Var A:
[[ 0.  0.]]

Var B:
[[ 0.41684544  0.05444515]]



### Session
#### Usages
A Session obj has the env. where Operation objects are executed, Tensor objects are evaluated.

```python
   
    # build the graph with tensors & ops
    a = tf.constant(5.0)
    b = tf.constant(6.0)
    c = a * b
    
    # launch the graph in a session.
    sess = tf.Session()
    
    # evaluate the tensor 'c'
    print(sess.run(c))
    
    # close the session to release resources.
    sess.close()
```

Alternatively, session can be used as a context manager. The two ways are equivalent.

```python
# open a session as a context manager
with tf.Session() as sess:
    
    # build the graph with tensors & ops
    a = tf.constant(5.0)
    b = tf.constant(6.0)
    c = a * b
    
    # Evaluate the tensor 'c'
    print(c.eval())
```

#### Session.run()
**KEY API**: *tf.Session.run(fetches, feed_dict=None, options=None, run_metadata=None)*

"Runs operations and evaluates tensors in **fetches**." --T.F.Doc

The fetches can be a graph element (a Tensor, an operation, etc.), or a list, tulple or dict that contains graph elements.

The feed_dict argument is optional. It "*allows the caller to override the value of tensors in graph.*" Within it, the key can be a Tensor, or a nested tulple of Tensors.


In [183]:
# For Explain Variables..

with tf.Session() as sess:   
    # create a variable
    var_1 = tf.Variable(tf.zeros([1,2]))
    var_2 = tf.Variable(tf.random_uniform([1,2]))
    
    # Inistialize vars
    init = tf.initialize_variables([var_1, var_2], name='init')
    # tf.initialize_all_variables().run()
    
    # Assignement Ops.
    # Which adds the ops to the graph, not performed yet.
    update_var1 = tf.assign(var_1, tf.random_uniform([1,2], -1.0, 1.0))  # op is random again
    update_var2 = tf.assign(var_2, tf.add(var_1, var_2))  # op is addition
    
    for _ in range(5):
        sess.run(init)
        sess.run(update_var1)
        sess.run(update_var2)
    
        print var_1.eval(), var_2.eval()
   

[[ 0.39782119 -0.46190071]] [[ 1.33713818 -0.3148371 ]]
[[-0.75201368  0.53828597]] [[-0.25756526  1.5165832 ]]
[[ 0.37571168 -0.87970138]] [[ 0.995368    0.06478631]]
[[-0.21329546  0.6940155 ]] [[ 0.67102897  0.89374876]]
[[ 0.47788572  0.59717727]] [[ 0.97123277  1.40898335]]


#### Note: The computation is only performed on demand.
                                                                            
                                                                           (will keep updating..)