In [148]:
import tensorflow as tf
import numpy as np

def print_msg( str1, str2 ):
    "This prints a msg.."
    print str1
    print str2 + "\n"
    return

# Open a session
with tf.Session() as sess:
    # create a constant
    cons_1 = tf.constant(1.0, np.float32,[3,8])
    print_msg("cons_1", str(cons_1.eval()))
    
    cons_2 = tf.constant(2.0, shape=[4]) # shape=[4] means the 1-d array with columns 4.
    print_msg("cons_2", str(cons_2.eval()))
    
    # simple calc
    cons_3 = tf.constant([4.0, 5.0, 6.0, 7.0])
    output = tf.add(cons_2, cons_3)
    print_msg("Cons2 + Cons3:", str(output.eval()))
    
    # reshape
    cons_1r = tf.reshape(cons_1, shape=[4,6])
    print_msg("Reshape Cons1:", str(cons_1r.eval()))
    
    # range
    cons_3 = tf.range(1, 19)
    print_msg("cons_3", str(cons_3.eval()))
    cons_3r = tf.reshape(cons_3, shape=[3, 6])
    print_msg("Reshape cons_3:", str(cons_3r.eval()))
    

cons_1
[[ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]]

cons_2
[ 2.  2.  2.  2.]

Cons2 + Cons3:
[ 6.  7.  8.  9.]

Reshape Cons1:
[[ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]]

cons_3
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]

Reshape cons_3:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]



### Tensors
    
>"*A vector is a 1-d array and is known as a 1st-order tensor. 
  A matrix is a 2-d array and a 2nd-order tensor. 
  The "flow" part of the name refers to computation flowing through a graph.*" -- T.F.
    
a vector is a single dimensional array. v(1i) means the array [1].
a plane vector is a 1 dimensional array. v(3i, 2j) => [3, 2]
a space vector is a 1 dimensional array. v(3i, 2j, 4z) => [3, 2, 4]
a vector of dimension n could be representing by an array of n elements.
    
#### a matrix is a 2-dimensional array. 
$\begin{bmatrix}
        1. \\
        2. \\
        3. \\
\end{bmatrix}$ => 
[ [1], [2], [3] ]
    
a normal matrix is like:
$\begin{bmatrix}
        2. & 4. & 5. \\
        3. & 10. & 6. \\
        11. & 9. & 3. \\
\end{bmatrix}$  => 
[ [ 2, 4, 5],
  [3, 10, 6],
  [11, 9, 3] ]
    
#### Temp-conclusion
Tensor is something multi-dimensional, especially useful in a large dimensional situation, and it has some same properties as vectors & matrices. e.g. calculations ..

In [ ]:
print "Variables Usage"

# create two vars.
# Variable class constructor(initial_value, name=<optional_name>) 
# initial_value can be any Tensor. Type + Shape.
weights = tf.Variable(tf.random_normal([784,200], stddev=0.35), name="weights")
biases = tf.Variable(tf.zeros([200]), name="biases")



# eval() is the trigger to get the result, where is also the graph computes.

